import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <StoreProvider>
        <body className="flex flex-col max-w-7xl items-center m-auto">
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
